### ISSUE TITLE
bot wont start

### ISSUE THREAD

**Issue by drandrew666** [EC-discord/self-bot#1]
Tried installing, and it wont start

**Comment by drandrew666** [comment]
How do I install this with discord?

**Comment by EC-discord** [comment]
did u give the bot your account token? it wont run without that

**Comment by EC-discord** [comment]
do you get some kind of error code when you try starting it? posting that might help debug it

**Comment by drandrew666** [comment]
Here is my error
I know it has some requirements but I cant find certain ones

Active code page: 65001

Traceback (most recent call last):
  File "selfbot.py", line 3, in <module>
    from ext.context import CustomContext
  File "C:\Users\Andrew\Desktop\self-bot-master\self-bot-master\ext\context.py", line 4, in <module>
    from colorthief import ColorThief
ImportError: No module named 'colorthief'
Press any key to continue . . .

**Comment by drandrew666** [comment]
Here is another error:

Active code page: 65001

  File "selfbot.py", line 36
    self.load_extension(f'{path}{extension}')
                                           ^
SyntaxError: invalid syntax
Press any key to continue . . .

**Comment by EC-discord** [comment]
try installing the module manually using pip install colorthief

**Comment by drandrew666** [comment]
Here's the error I get right when it starts up:

Active code page: 65001

  File "selfbot.py", line 36
    self.load_extension(f'{path}{extension}')
                                           ^
SyntaxError: invalid syntax
Press any key to continue . . .

**Comment by drandrew666** [comment]
Pip install colorthief worked but now im getting the above issue

**Comment by EC-discord** [comment]
what version of python are you using?

**Comment by drandrew666** [comment]
3.5.6

**Comment by EC-discord** [comment]
try updating to 3.6.6 or 3.6.8

**Comment by drandrew666** [comment]
Tried both and I got a new error:

Active code page: 65001

Traceback (most recent call last):
  File "selfbot.py", line 1, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'
Press any key to continue . . .

**Comment by EC-discord** [comment]
py -{version} -m pip install discord.py
this should fix the issue, {version} is your python version number, the one you upgraded to

**Comment by drandrew666** [comment]
That imported discord.py perfectly, here's the next error i've been getting:
Active code page: 65001

LoadError: Anim
AttributeError: module 'discord.ext.commands' has no attribute 'Cog'
LoadError: EC
AttributeError: module 'discord.ext.commands' has no attribute 'Cog'
LoadError: misc
ModuleNotFoundError: No module named 'emoji'
LoadError: mod
AttributeError: module 'discord.ext.commands' has no attribute 'Cog'
LoadError: noble
ModuleNotFoundError: No module named 'moviepy'
LoadError: skid
ModuleNotFoundError: No module named 'mtranslate'
LoadError: source
AttributeError: module 'discord.ext.commands' has no attribute 'Cog'
LoadError: utils
ModuleNotFoundError: No module named 'mtranslate'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 857, in on_message
    yield from self.process_commands(message)
  File "selfbot.py", line 105, in process_commands
    ctx = await self.get_context(message, cls=CustomContext)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Selfbot'>' object has no attribute 'get_context'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 857, in on_message
    yield from self.process_commands(message)
  File "selfbot.py", line 105, in process_commands
    ctx = await self.get_context(message, cls=CustomContext)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Selfbot'>' object has no attribute 'get_context'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 857, in on_message
    yield from self.process_commands(message)
  File "selfbot.py", line 105, in process_commands
    ctx = await self.get_context(message, cls=CustomContext)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Selfbot'>' object has no attribute 'get_context'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 857, in on_message
    yield from self.process_commands(message)
  File "selfbot.py", line 105, in process_commands
    ctx = await self.get_context(message, cls=CustomContext)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Selfbot'>' object has no attribute 'get_context'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 857, in on_message
    yield from self.process_commands(message)
  File "selfbot.py", line 105, in process_commands
    ctx = await self.get_context(message, cls=CustomContext)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Selfbot'>' object has no attribute 'get_context'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 857, in on_message
    yield from self.process_commands(message)
  File "selfbot.py", line 105, in process_commands
    ctx = await self.get_context(message, cls=CustomContext)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Selfbot'>' object has no attribute 'get_context'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 857, in on_message
    yield from self.process_commands(message)
  File "selfbot.py", line 105, in process_commands
    ctx = await self.get_context(message, cls=CustomContext)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Selfbot'>' object has no attribute 'get_context'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 857, in on_message
    yield from self.process_commands(message)
  File "selfbot.py", line 105, in process_commands
    ctx = await self.get_context(message, cls=CustomContext)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Selfbot'>' object has no attribute 'get_context'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 857, in on_message
    yield from self.process_commands(message)
  File "selfbot.py", line 105, in process_commands
    ctx = await self.get_context(message, cls=CustomContext)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Selfbot'>' object has no attribute 'get_context'

**Comment by EC-discord** [comment]
o God, these errors just keep getting bigger and bigger
pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
pip install emoji
pip install moviepy
pip install mtranslate
this should work

**Comment by drandrew666** [comment]
This error when installing discord.py (I ran it as an admin):
Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\Andrew\\AppData\\Local\\Temp\\pip-uninstall-9fsl445z\\users\\andrew\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\discord\\bin\\libopus-0.x86.dll'
Consider using the `--user` option or check the permissions.

And I got this error when trying to run it:
Active code page: 65001

Traceback (most recent call last):
  File "selfbot.py", line 4, in <module>
    from ext.formatter import EmbedHelp
  File "C:\Users\Andrew\Desktop\self-bot-master\self-bot-master\ext\formatter.py", line 125, in <module>
    class EmbedHelp(commands.HelpFormatter):
AttributeError: module 'discord.ext.commands' has no attribute 'HelpFormatter'
Press any key to continue . . .

**Comment by EC-discord** [comment]
the error is due to the recent breaking changes( the second error ) you might want to refork the repo for the new one

**Comment by drandrew666** [comment]
I have no idea what that means, sorry xD

**Comment by EC-discord** [comment]
redownload this repository

**Comment by EC-discord** [comment]
like redownload the bot
